project:
  type: website

website:
  title: "Saṃsāra"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/samsaara
format:
  html:
    theme: solar
    css: styles.css



